def build_create_schedule_request(
    subject, threadId, etag, meetingUrl, links, teamsVtcTenantId, senderMri, organizerAddress, organizerName, html
):
    return {
        "calendarEvent": {
            "startTime": "2023-09-12T22:25:00+02:00",
            "endTime": "2023-09-12T22:30:00+02:00",
            "eventTimeZone": "RomanceSt",
            "utcOffset": 120,
            "eventType": "Single",
            "subject": subject,
            "location": "",
            "skypeTeamsData": '{"uid":"' + senderMri + '","type":0,"private":True}',
            "joinMeetingLabel": "Join the Microsoft Teams online conference",
            "emptyBodyPlaceholder": "Has scheduled a meeting",
            "isAllDayEvent": False,
            "organizerName": "organizerName",
            "organizerAddress": "organizerAddress",
            "isResponseRequested": True,
            "attendees": [
                {
                    "type": "Organizer",
                    "address": organizerAddress,
                    "name": organizerName,
                    "mri": senderMri,
                    "role": "Admin",
                }
            ],
            "isReminderSet": True,
            "reminderMinutesBeforeStart": 15,
            "showAs": "Busy",
            "isPrivate": False,
            "bodyContent": "<p></p>",
            "isOrganizer": True,
            "isAppointment": True,
            "primarySpokenLanguage": "en-us",
            "clientOptimisticEventId": "8492165730-3654879210-7025149863-1938250476-5284639107",
            "doNotForward": False,
            "meetingTemplateId": "default",
            "sensitivityLabelId": "",
        },
        "schedulingServiceEvent": {
            "startTime": None,
            "endTime": None,
            "subject": None,
            "groupContext": {"threadId": threadId},
            "etag": '"' + etag + '"',
            "meetingUrl": meetingUrl,
            "links": links,
            "views": {"html": html},
            "onlineMeetingConfLink": None,
            "onlineMeetingConferenceId": None,
            "onlineMeetingTollFreeNumbers": None,
            "onlineMeetingTollNumber": None,
            "teamsVtcTenantId": teamsVtcTenantId,
            "teamsVtcConferenceId": None,
        },
        "meetingOptions": [
            {"name": "AutoAdmittedUsers", "type": "List", "currentValue": "EveryoneInCompany"},
            {"name": "AllowPstnUsersToBypassLobby", "type": "Boolean", "currentValue": False},
            {"name": "EntryExitAnnouncementsEnabled", "type": "Boolean", "currentValue": False},
            {"name": "PresenterOption", "type": "List", "currentValue": "Everyone"},
            {"name": "AttendeeRestrictions", "type": "BitMask", "currentValue": "UnRestricted"},
            {"name": "AutoRecordingEnabled", "type": "Boolean", "currentValue": False},
            {"name": "AllowMeetingChat", "type": "List", "currentValue": "Enabled"},
            {"name": "YammerQNAEnabled", "type": "Boolean", "currentValue": False},
            {"name": "AllowTeamsMeetingReactions", "type": "Boolean", "currentValue": True},
            {"name": "Interpretation", "type": "Interpretation", "currentValue": False, "interpreters": None},
        ],
    }
